### ISSUE TITLE
com.squareup.protoparser.EnumType$Value cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by cecol** [square/protoparser#95] opened 2015-05-23 13:26 UTC
Hi, first of all, thank you for your contribution
The thing is when I try to check a MessageType.Field has default or not
I use =>  if (field.getDefault() != null)
but I get exception:
com.squareup.protoparser.EnumType$Value cannot be cast to java.lang.String

the original .proto defined is
optional PhoneType type = 2 [default = HOME];
(same as official example Person message: https://developers.google.com/protocol-buffers/docs/javatutorial) 

is any misunderstanding or mistake in my code?
(my source code https://github.com/cecol/protobuf-to-avro/blob/dev/src/main/java/wilber/com/transform/ProtoSchema.java)

**Comment by JakeWharton** [comment] 2015-05-25 07:54
Dupe of #90.

I would urge you to try 4.0.0-SNAPSHOT as the release is imminent. It's re-think of the model and it's much more sane for handling parsed data. I'm going to try to publish a 3.1.6 that fixes this issue after 4.0.0's release though.

**Closed by JakeWharton** 2015-05-25 07:54 UTC
